---
- name: Install light-NGINX / PHP and modules
  apt:
          pkg:
                  - nginx-light
                  - php-amqp
                  - php-curl
                  - php-fpm
                  - php-gd
                  - php-intl
                  - php-mbstring
                  - php-memcached
                  - php-pgsql
                  - php-redis
                  - php-xml
                  - git
          state: latest
          update_cache: true

- name: Push the development PHP-FPM Configuration
  copy:
          src: files/php-development.fpm.ini
          dest: /etc/php/7.3/fpm/php.ini
          mode: 0644
          owner: root

- name: Push the PHP-CLI Configuration
  copy:
          src: files/php.cli.ini
          dest: /etc/php/7.3/cli/php.ini
          mode: 0644
          owner: root

- name: Push Symfony virtual host configuration
  copy:
          src: files/symfony
          dest: /etc/nginx/sites-available/symfony
          mode: 0644
          owner: root

- name: Create Symfony log repository
  file:
          path: /var/log/nginx/symfony
          state: directory

- name: Check our configuration
  command: nginx -t
  register: result
  ignore_errors: True

- name: Rolling back - Removing our log repository
  file:
          path: /var/log/nginx/symfony
          state: absent
  when: result is failed

- name: Rolling back - Removing our virtualhost
  file:
          path: /etc/nginx/sites-available/symfony
          state: absent
  when: result is failed

- name: Rolling back - Ending playbook
  fail:
          msg: "ERROR: Nginx configuration file is not valid. Please check that before re-running the playbook."
  when: result is failed

- name: Create web Symfony repository (env=dev)
  file:
          path: /var/www/symfony
          state: directory
          mode: 0755
          owner: www-data
          group: www-data

- name: Push PHP test file
  copy:
          src: files/index.php
          dest: /var/www/symfony/index.php
          mode: 0644
          owner: www-data
          group: www-data

- name: Activate symfony virtualhost
  file:
          src: /etc/nginx/sites-available/symfony
          dest: /etc/nginx/sites-enabled/symfony
          state: link
  notify:
          - Reload nginx

- name: Disable the default Nginx virtualhost
  file:
          dest: /etc/nginx/sites-enabled/default
          state: absent
  notify:
          - Reload nginx

- name: Push Composer installer
  copy:
          src: files/composer_install.sh
          dest: /opt/composer_install.sh
          mode: 0744

- name: Install Composer
  command: sh /opt/composer_install.sh
  register: result
  ignore_errors: True

- name: Rolling back - Removing installer
  file:
          path: /opt/composer_install.sh
          state: absent
  when: result is failed

- name: Rolling back - Ending playbook
  fail:
          msg: "ERROR: Impossible to install Composer. Please check that before re-running the playbook."
  when: result is failed

- name: Pull Symfony CLI installer
  command: wget https://get.symfony.com/cli/installer -O /opt/symfony_install.sh

- name: Install Symfony CLI
  command: bash /opt/symfony_install.sh --install-dir=/usr/local/bin
  register: result
  ignore_errors: True

- name: Rolling back - Ending playbook
  fail:
          msg: "ERROR: Impossible to install Symfony CLI. Please check that before re-running the playbook."
  when: result is failed
