---
- name: Install the base packages
  apt:
          pkg:
                  - figlet
                  - git
                  - openjdk-11-jre
                  - python-pip
                  - python3-pip
          install_recommends: no
          state: latest
