---
- name: Install PHP-FPM and modules
  apt:
          pkg:
                  - php-amqp
                  - php-curl
                  - php-fpm
                  - php-gd
                  - php-intl
                  - php-mbstring
                  - php-memcached
                  - php-pgsql
                  - php-redis
                  - php-xml
                  - php-zip
          state: latest
          update_cache: true

- name: Push the PHP-CLI Configuration
  copy:
          src: templates/php.cli.ini
          dest: /etc/php/7.3/cli/php.ini
          mode: 0644
          owner: root

- name: Push the development PHP-FPM Configuration
  copy:
          src: templates/php-development.fpm.ini
          dest: /etc/php/7.3/fpm/php.ini
          mode: 0644
          owner: root
  notify:
          - Reload php-fpm

- name: Ensure PHP-FPM is running
  systemd:
          name: php7.3-fpm
          state: started
  register: result
  ignore_errors: True

- name: PHP-FPM - Ending playbook
  fail:
          msg: "ERROR: PHP-FPM configuration file is not valid. Please check that before re-running the playbook."
  when: result is failed

- name: Push Composer installer
  copy:
          src: files/composer_install.sh
          dest: /opt/composer_install.sh
          mode: 0744

- name: Install Composer
  command: bash /opt/composer_install.sh
  register: result
  ignore_errors: True

- name: Rolling back - Removing installer
  file:
          path: /opt/composer_install.sh
          state: absent
  when: result is failed

- name: Rolling back - Ending playbook
  fail:
          msg: "ERROR: Impossible to install Composer. Please check that before re-running the playbook."
  when: result is failed

- name: Pull Symfony CLI installer
  command: wget https://get.symfony.com/cli/installer -O /opt/symfony_install.sh

- name: Install Symfony CLI
  command: bash /opt/symfony_install.sh --install-dir=/usr/local/bin
  register: result
  ignore_errors: True

- name: Rolling back - Ending playbook
  fail:
          msg: "ERROR: Impossible to install Symfony CLI. Please check that before re-running the playbook."
  when: result is failed
