---
####.
#
# Overview: Playbook to bootstrap a new NGINX server for configuration management.
# Applies to: default
# Description:
#   Ensures that a host has NGINX installed
#
###########
- hosts: debian10
  tasks:
          - name: Push the complete source list
            copy:
                    src: files/default/apt/sources.list
                    dest: /etc/apt/sources.list
                    mode: 0644
            notify: Update APT

          - name: Install the base packages
            apt:
                    pkg:
                            - sudo
                            - htop
                            - bash-completion
                            - vim
                            - indent
                            - ctags
                    install_recommends: no
                    state: latest
                    update_cache: true

  handlers:
          - name: Update APT
            apt:
                    autoclean: yes
                    autoremove: yes
                    install_recommends: no
                    purge: yes
                    upgrade: full
                    update_cache: yes

