---

- hosts: no_reboot
  tasks:
    - name: Update all installed packages using APT module
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
        autoremove: yes
        autoclean: yes

- hosts: symfony
  tasks:
    - name: Update all installed packages using APT module
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
        autoremove: yes
        autoclean: yes
      notify: Reboot

  handlers:
    - name: Reboot
      reboot:
        post_reboot_delay: 60
