---

- hosts: no_reboot
  tasks:
    - name: Update all installed packages using APT module
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
        autoremove: yes
        autoclean: yes

- hosts: symfony
  tasks:
    - name: Update all installed packages using APT module
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
        autoremove: yes
        autoclean: yes
      register: apt_update_status

    - name: Reboot when packages were updated
      reboot:
        post_reboot_delay: 60
      when: apt_update_status.changed
