---

- name: Push the complete source list
  copy:
    backup: true
    src: templates/virtualbox.list
    dest: /etc/apt/virtualbox.list
    mode: 0644
  notify: Update APT

- name: Install the base packages
  apt:
    pkg:
      - virtualbox-6.1
    install_recommends: no
    state: latest
    update_cache: true

- name: Download the additions
  get_url:
    url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack"
    dest: "/opt/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack"
    mode: 0755
