---
- name: Install required packages
  apt:
    pkg:
      - ssh
    install_recommends: no
    state: latest
  tags:
    - install_packages

- name: Ensure SSHd config is in place
  copy:
    backup: yes
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify: Reload SSHd

- name: Ensure global SSH config is in place
  copy:
    backup: yes
    src: files/ssh_config
    dest: /etc/ssh/ssh_config
    mode: 0644

- name: Ensure user SSH config is in place
  copy:
    backup: yes
    src: "files/ssh.{{ user }}"
    dest: "/home/{{ user }}/.ssh/config"
    mode: 0600
    owner: "{{ user }}"
    group: "{{ user }}"
