---
- name: Update APT
  apt:
          autoclean: yes
          autoremove: yes
          install_recommends: no
          purge: yes
          upgrade: full
          update_cache: yes

- name: Reload SSH
  systemd:
          name: ssh
          state: reloaded
