---
- name: Update APT
  apt:
          autoclean: yes
          autoremove: yes
          install_recommends: no
          purge: yes
          upgrade: full
          update_cache: yes

- name: Restart crond
  systemd:
          name: cron
          state: restarted
          daemon_reload: yes
