---
- name: Install the base packages
  apt:
    pkg:
      - most
    install_recommends: no
    state: latest

- name: Ensure Most is the default Pager
  lineinfile:
    path: "/home/{{ user }}/"
    regexp: '^export PAGER='
    line: export PAGER=most
    with_items:
      - "/home/{{ user }}/.bashrc"
      - "/root/.bashrc"
