---
- name: Backup the original source list
  command: cp -a /etc/apt/sources.list /etc/apt/sources.list.dist

- name: Push the complete source list
  copy:
          src: templates/sources.list
          dest: /etc/apt/sources.list
          mode: 0644
  notify: Update APT

- name: Install the base packages
  apt:
          pkg:
                  - bash-completion
                  - dos2unix
                  - htop
                  - pigz
                  - tree
                  - vim
                  - sudo
          install_recommends: no
          state: latest
          update_cache: true
