---
- name: Backup the original source list
  command: cp -a /etc/apt/sources.list /etc/apt/sources.list.dist
  tags: install

- name: Push the complete source list
  copy:
          src: templates/sources.list
          dest: /etc/apt/sources.list
          mode: 0644
  notify: Update APT

- name: Install the base packages
  apt:
          pkg:
                  - bash-completion
                  - dos2unix
                  - htop
                  - pigz
                  - tree
                  - vim
                  - sudo
          install_recommends: no
          state: latest
          update_cache: true

- name: Add the user in the sudo group
  user:
          name: "{{ user }}"
          group: sudo
          append: yes

- name: Configure Timesyncd
  copy:
          src: templates/timesyncd.conf
          dest: /etc/systemd/timesyncd.conf
          mode: 0644

- name: Set the timezone
  timezone:
          name: "{{ timezone }}"
  notify: Restart crond

- name: Ensure EN locale exists
  locale_gen:
          name: "en_US.UTF-8"
          state: present

- name: Ensure local locale exists
  locale_gen:
          name: "{{ locale }}"
          state: present

- name: Set the locale
  command: "localectl set-locale LANG={{ locale }}"

- name: Generate the new locale
  command: locale-gen

- name: Push bashrc file for my user
  copy:
          src: templates/bashrc
          dest: "/home/{{ user }}/.bashrc"
          mode: 0644

- name: Push alias config file for standard user
  copy:
          src: templates/bash_aliases
          dest: "/home/{{ user }}/.bash_aliases"
          mode: 0644

- name: Push vim config file for standard user
  copy:
          src: templates/vimrc
          dest: "/home/{{ user }}/.vimrc"
          mode: 0644

- name: Push bashrc file for the user root
  copy:
          src: templates/bashrc-root
          dest: /root/.bashrc
          mode: 0644

- name: Push alias config file for user root
  copy:
          src: templates/bash_aliases
          dest: /root/.bash_aliases
          mode: 0644

- name: Push vim config file for user root
  copy:
          src: templates/vimrc
          dest: /root/.vimrc
          mode: 0644
