---
- name: Ensure basic source list is in place
  copy:
    backup: yes
    src: files/sources.list
    dest: /etc/apt/sources.list
    mode: 0644
  notify: Update APT
  tags:
    - install_packages

- name: Install common packages
  apt:
    pkg:
      - bash-completion
      - ccze
      - dfc
      - dos2unix
      - htop
      - lnav
      - needrestart
      - pigz
      - tree
      - sudo
    install_recommends: no
    state: latest
  tags:
    - install_packages

- name: Ensure user is in the sudo group
  user:
    name: "{{ user }}"
    group: sudo
    append: yes

- name: Configure Timesyncd
  copy:
    backup: yes
    src: files/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: 0644

- name: Set the timezone
  timezone:
    name: "{{ timezone }}"
  notify: Restart crond

- name: Ensure EN locale exists
  locale_gen:
    name: "en_US.UTF-8"
    state: present

- name: Ensure local locale exists
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: Set the locale
  command: "localectl set-locale LANG={{ locale }}"

- name: Generate the new locale
  command: locale-gen

- name: Ensure bashrc file is in place
  copy:
    backup: yes
    src: files/bashrc
    dest: "/home/{{ user }}/.bashrc"
    mode: 0644

- name: Ensure aliases are in place
  copy:
    backup: yes
    src: files/bash_aliases
    dest: "/home/{{ user }}/.bash_aliases"
    mode: 0644

- name: Ensure bashrc is in place for root
  copy:
    backup: yes
    src: files/bashrc.root
    dest: /root/.bashrc
    mode: 0600

- name: Ensure aliases are in place for root
  copy:
    backup: yes
    src: files/bash_aliases
    dest: /root/.bash_aliases
    mode: 0600
