---

- name: Install required packages
  apt:
          pkg:
                  - vim
                  - fonts-powerline
          install_recommends: no
          state: latest
  become: yes
  tags:
          - install_packages

- name: Ensure .vim/{autoload,bundle} directory exists
  file:
          path: "{{ item }}"
          state: directory
          recurse: no
          mode: 0750
  loop:
          - "/home/{{ user }}/.vim"
          - "/home/{{ user }}/.vim/autoload"
          - "/home/{{ user }}/.vim/bundle"

- name: Ensure Pathogen is in place
  get_url:
          dest: "/home/{{ user }}/.vim/autoload/pathogen.vim"
          url: https://tpo.pe/pathogen.vim

- name: Deploy plugins
  git:
          dest: "/home/{{ user }}/.vim/bundle/{{ item.name }}"
          repo: "{{ item.url }}"
          clone: yes
          update: yes
          recursive: no
  loop:
          - name: dracula
            url: https://github.com/dracula/vim
          - name: solarized
            url: https://github.com/altercation/vim-colors-solarized

- name: Ensure .vimrc config in place
  copy:
          src: vimrc
          dest: "/home/{{ user }}/.vimrc"
          backup: yes
          mode: 0640

- name: Ensure .vimrc config in place for root
  copy:
          src: vimrc.root
          dest: "/root/.vimrc"
          backup: yes
          mode: 0640
          become: yes
